name: pizza_reader
description: "Client-side fast reading app with ebook import and Supabase sync."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.9
  crypto: ^3.0.7
  cupertino_icons: ^1.0.8
  file_picker: ^10.2.4
  html: ^0.15.6
  supabase_flutter: ^2.12.4
  xml: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/brand/pizzalogo.png
    - assets/illustrations/
